# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabriel/code/PAA/graph-bridge

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabriel/code/PAA/graph-bridge

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/code/PAA/graph-bridge/CMakeFiles /home/gabriel/code/PAA/graph-bridge//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/code/PAA/graph-bridge/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyProject

# Build rule for target.
MyProject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyProject
.PHONY : MyProject

# fast build rule for target.
MyProject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/build
.PHONY : MyProject/fast

code/eulerian.o: code/eulerian.cpp.o
.PHONY : code/eulerian.o

# target to build an object file
code/eulerian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/eulerian.cpp.o
.PHONY : code/eulerian.cpp.o

code/eulerian.i: code/eulerian.cpp.i
.PHONY : code/eulerian.i

# target to preprocess a source file
code/eulerian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/eulerian.cpp.i
.PHONY : code/eulerian.cpp.i

code/eulerian.s: code/eulerian.cpp.s
.PHONY : code/eulerian.s

# target to generate assembly for a file
code/eulerian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/eulerian.cpp.s
.PHONY : code/eulerian.cpp.s

code/graph/graph.o: code/graph/graph.cpp.o
.PHONY : code/graph/graph.o

# target to build an object file
code/graph/graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/graph/graph.cpp.o
.PHONY : code/graph/graph.cpp.o

code/graph/graph.i: code/graph/graph.cpp.i
.PHONY : code/graph/graph.i

# target to preprocess a source file
code/graph/graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/graph/graph.cpp.i
.PHONY : code/graph/graph.cpp.i

code/graph/graph.s: code/graph/graph.cpp.s
.PHONY : code/graph/graph.s

# target to generate assembly for a file
code/graph/graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/graph/graph.cpp.s
.PHONY : code/graph/graph.cpp.s

code/graph/graph_reader.o: code/graph/graph_reader.cpp.o
.PHONY : code/graph/graph_reader.o

# target to build an object file
code/graph/graph_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/graph/graph_reader.cpp.o
.PHONY : code/graph/graph_reader.cpp.o

code/graph/graph_reader.i: code/graph/graph_reader.cpp.i
.PHONY : code/graph/graph_reader.i

# target to preprocess a source file
code/graph/graph_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/graph/graph_reader.cpp.i
.PHONY : code/graph/graph_reader.cpp.i

code/graph/graph_reader.s: code/graph/graph_reader.cpp.s
.PHONY : code/graph/graph_reader.s

# target to generate assembly for a file
code/graph/graph_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/graph/graph_reader.cpp.s
.PHONY : code/graph/graph_reader.cpp.s

code/main.o: code/main.cpp.o
.PHONY : code/main.o

# target to build an object file
code/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/main.cpp.o
.PHONY : code/main.cpp.o

code/main.i: code/main.cpp.i
.PHONY : code/main.i

# target to preprocess a source file
code/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/main.cpp.i
.PHONY : code/main.cpp.i

code/main.s: code/main.cpp.s
.PHONY : code/main.s

# target to generate assembly for a file
code/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/main.cpp.s
.PHONY : code/main.cpp.s

code/naive.o: code/naive.cpp.o
.PHONY : code/naive.o

# target to build an object file
code/naive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/naive.cpp.o
.PHONY : code/naive.cpp.o

code/naive.i: code/naive.cpp.i
.PHONY : code/naive.i

# target to preprocess a source file
code/naive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/naive.cpp.i
.PHONY : code/naive.cpp.i

code/naive.s: code/naive.cpp.s
.PHONY : code/naive.s

# target to generate assembly for a file
code/naive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/naive.cpp.s
.PHONY : code/naive.cpp.s

code/tarjan.o: code/tarjan.cpp.o
.PHONY : code/tarjan.o

# target to build an object file
code/tarjan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/tarjan.cpp.o
.PHONY : code/tarjan.cpp.o

code/tarjan.i: code/tarjan.cpp.i
.PHONY : code/tarjan.i

# target to preprocess a source file
code/tarjan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/tarjan.cpp.i
.PHONY : code/tarjan.cpp.i

code/tarjan.s: code/tarjan.cpp.s
.PHONY : code/tarjan.s

# target to generate assembly for a file
code/tarjan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/tarjan.cpp.s
.PHONY : code/tarjan.cpp.s

code/utils/randomizer.o: code/utils/randomizer.cpp.o
.PHONY : code/utils/randomizer.o

# target to build an object file
code/utils/randomizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/utils/randomizer.cpp.o
.PHONY : code/utils/randomizer.cpp.o

code/utils/randomizer.i: code/utils/randomizer.cpp.i
.PHONY : code/utils/randomizer.i

# target to preprocess a source file
code/utils/randomizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/utils/randomizer.cpp.i
.PHONY : code/utils/randomizer.cpp.i

code/utils/randomizer.s: code/utils/randomizer.cpp.s
.PHONY : code/utils/randomizer.s

# target to generate assembly for a file
code/utils/randomizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/code/utils/randomizer.cpp.s
.PHONY : code/utils/randomizer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MyProject"
	@echo "... code/eulerian.o"
	@echo "... code/eulerian.i"
	@echo "... code/eulerian.s"
	@echo "... code/graph/graph.o"
	@echo "... code/graph/graph.i"
	@echo "... code/graph/graph.s"
	@echo "... code/graph/graph_reader.o"
	@echo "... code/graph/graph_reader.i"
	@echo "... code/graph/graph_reader.s"
	@echo "... code/main.o"
	@echo "... code/main.i"
	@echo "... code/main.s"
	@echo "... code/naive.o"
	@echo "... code/naive.i"
	@echo "... code/naive.s"
	@echo "... code/tarjan.o"
	@echo "... code/tarjan.i"
	@echo "... code/tarjan.s"
	@echo "... code/utils/randomizer.o"
	@echo "... code/utils/randomizer.i"
	@echo "... code/utils/randomizer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

